# Generated by Django 6.0 on 2026-01-13 05:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_book_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadTask',
            fields=[
                ('task_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch_id', models.UUIDField(default=uuid.uuid4)),
                ('created_book_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.book')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch_id'], name='account_bul_batch_i_e161c6_idx'), models.Index(fields=['status'], name='account_bul_status_71d3a9_idx')],
            },
        ),
    ]
