# Generated by Django 6.0 on 2026-01-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_bulkuploadbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulkuploadtask',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='BulkUploadBatch',
        ),
    ]
