# Generated by Django 6.0 on 2026-01-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
